# Generated by Django 5.2.1 on 2025-06-16 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Administrator'), ('provider', 'Healthcare Provider'), ('caregiver', 'Caregiver'), ('patient', 'Patient')], max_length=20)),
                ('linked_patients', models.ManyToManyField(blank=True, help_text='Patients this caregiver can access', limit_choices_to={'user_type': 'patient'}, related_name='linked_caregivers', to='users.userprofile')),
                ('patient', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'patient'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregivers', to='users.userprofile')),
                ('provider', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_patients', to='users.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
