# Generated by Django 5.2.1 on 2025-05-31 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_patients', to='users.userprofile'),
        ),
    ]
