# Generated by Django 5.2.1 on 2025-05-31 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'patient'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregivers', to='users.userprofile'),
        ),
    ]
