# Generated by Django 5.2.1 on 2025-06-08 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
    ]
