# Generated by Django 5.2.1 on 2025-06-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairetemplate',
            name='task_type',
            field=models.CharField(choices=[('memory_questionnaire', 'Memory Questionnaire'), ('checklist', 'Checklist'), ('puzzle', 'Memory Puzzle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('memory_questionnaire', 'Memory Questionnaire'), ('checklist', 'Checklist'), ('puzzle', 'Memory Puzzle')], max_length=50),
        ),
    ]
