# Generated by Django 5.2.1 on 2025-06-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_alter_questionnairetemplate_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairetemplate',
            name='task_type',
            field=models.CharField(choices=[('memory_questionnaire', 'Memory Questionnaire'), ('checklist', 'Checklist'), ('puzzle', 'Memory Puzzle'), ('color', 'Color Matching')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('memory_questionnaire', 'Memory Questionnaire'), ('checklist', 'Checklist'), ('puzzle', 'Memory Puzzle'), ('color', 'Color Matching')], max_length=50),
        ),
    ]
