# Generated by Django 5.2.1 on 2025-06-19 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_appointment'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], help_text='Cognitive difficulty level for games', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
