# Generated by Django 5.2.1 on 2025-06-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_setup_difficulty_system'),
    ]

    operations = [
    ]
