# Generated by Django 5.2.1 on 2025-06-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_fix_task_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('major', 'Major')], default='mild', help_text='Cognitive difficulty level for games', max_length=20),
        ),
    ]
